"""added time to complete for polls

Revision ID: 02068d2873bf
Revises: e4b3a2ce181e
Create Date: 2023-10-14 17:15:00.228472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02068d2873bf'
down_revision = 'e4b3a2ce181e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('time_to_complete', sa.Integer(), nullable=False))
    op.alter_column('users', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'https://mykaleidoscope.ru/x/uploads/posts/2023-05/1684818829_mykaleidoscope-ru-p-strizhka-stasa-pekhi-pinterest-69.jpg'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'https://mykaleidoscope.ru/x/uploads/posts/2023-05/1684818829_mykaleidoscope-ru-p-strizhka-stasa-pekhi-pinterest-69.jpg'::character varying"))
    op.drop_column('polls', 'time_to_complete')
    # ### end Alembic commands ###
