"""added is_solved property to problems table

Revision ID: 549cefde9d61
Revises: b6033efcc097
Create Date: 2023-10-10 16:49:55.310600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549cefde9d61'
down_revision = 'b6033efcc097'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll_questions', sa.Column('entry_id', sa.Integer(), nullable=False))
    op.add_column('problems', sa.Column('is_solved', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'is_solved')
    op.drop_column('poll_questions', 'entry_id')
    # ### end Alembic commands ###
