"""added min_max_response to poll_questions

Revision ID: 57c279d25d1a
Revises: 8a5d0ba68452
Create Date: 2023-10-09 18:00:24.318069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c279d25d1a'
down_revision = '8a5d0ba68452'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('poll_questions', sa.Column('min_responses', sa.Integer(), server_default='1', nullable=False))
    op.add_column('poll_questions', sa.Column('max_responses', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll_questions', 'max_responses')
    op.drop_column('poll_questions', 'min_responses')
    op.drop_table('posts')
    # ### end Alembic commands ###
