"""added info about tags

Revision ID: 8fb0670ab31a
Revises: 549cefde9d61
Create Date: 2023-10-11 23:55:19.666005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb0670ab31a'
down_revision = '549cefde9d61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'info')
    # ### end Alembic commands ###
