"""added images columns

Revision ID: b6033efcc097
Revises: e1b1fd2bf7cc
Create Date: 2023-10-10 16:08:35.474502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b6033efcc097"
down_revision = "e1b1fd2bf7cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "problems",
        sa.Column(
            "images",
            postgresql.ARRAY(sa.String(), dimensions=1, zero_indexes=True),
            nullable=True,
            server_default="{}",
        ),
    )
    op.add_column("users", sa.Column("profile_image", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_image")
    op.drop_column("problems", "images")
    # ### end Alembic commands ###
