"""added name surname role age sex to users table

Revision ID: da54be5cab01
Revises: c8cd00b2c6ac
Create Date: 2023-10-02 22:32:32.351025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da54be5cab01"
down_revision = "c8cd00b2c6ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(), nullable=False))
    op.add_column("users", sa.Column("surname", sa.String(), nullable=False))
    op.add_column(
        "users", sa.Column("role", sa.String(), nullable=False, server_default="-")
    )
    op.add_column(
        "users", sa.Column("age", sa.Integer(), nullable=False, server_default="1")
    )
    op.add_column(
        "users", sa.Column("sex", sa.String(), nullable=False, server_default="N")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "sex")
    op.drop_column("users", "age")
    op.drop_column("users", "role")
    op.drop_column("users", "surname")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
