"""added verification_code

Revision ID: ddc5209ae8f9
Revises: da54be5cab01
Create Date: 2023-10-03 23:43:53.050889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ddc5209ae8f9"
down_revision = "da54be5cab01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("verification_code", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "users", ["verification_code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_verification_code_key", "users", type_="unique")
    op.drop_column("users", "verification_code")
    # ### end Alembic commands ###
