"""added properties to polls table

Revision ID: fad115c5c847
Revises: ab8487a383e7
Create Date: 2023-10-07 23:20:46.112029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fad115c5c847"
down_revision = "ab8487a383e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "polls",
        sa.Column("is_anonymous", sa.Boolean(), server_default="False", nullable=False),
    )
    op.add_column("polls", sa.Column("creator_id", sa.Integer(), nullable=True))
    op.add_column(
        "polls",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "polls_creator_id_fkey",
        "polls",
        "users",
        ["creator_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("polls_creator_id_fkey", "polls", type_="foreignkey")
    op.drop_column("polls", "created_at")
    op.drop_column("polls", "creator_id")
    op.drop_column("polls", "is_anonymous")
    # ### end Alembic commands ###
